package com.singulee.carschool.pojo;

import java.util.Date;

public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.courseId
     *
     * @mbg.generated
     */
    private Integer courseid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.courseName
     *
     * @mbg.generated
     */
    private String coursename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.courseBegin
     *
     * @mbg.generated
     */
    private Date coursebegin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.courseEnd
     *
     * @mbg.generated
     */
    private Date courseend;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.courseId
     *
     * @return the value of course.courseId
     *
     * @mbg.generated
     */
    public Integer getCourseid() {
        return courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.courseId
     *
     * @param courseid the value for course.courseId
     *
     * @mbg.generated
     */
    public void setCourseid(Integer courseid) {
        this.courseid = courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.courseName
     *
     * @return the value of course.courseName
     *
     * @mbg.generated
     */
    public String getCoursename() {
        return coursename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.courseName
     *
     * @param coursename the value for course.courseName
     *
     * @mbg.generated
     */
    public void setCoursename(String coursename) {
        this.coursename = coursename == null ? null : coursename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.courseBegin
     *
     * @return the value of course.courseBegin
     *
     * @mbg.generated
     */
    public Date getCoursebegin() {
        return coursebegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.courseBegin
     *
     * @param coursebegin the value for course.courseBegin
     *
     * @mbg.generated
     */
    public void setCoursebegin(Date coursebegin) {
        this.coursebegin = coursebegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.courseEnd
     *
     * @return the value of course.courseEnd
     *
     * @mbg.generated
     */
    public Date getCourseend() {
        return courseend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.courseEnd
     *
     * @param courseend the value for course.courseEnd
     *
     * @mbg.generated
     */
    public void setCourseend(Date courseend) {
        this.courseend = courseend;
    }
}