package com.singulee.carschool.pojo;

import java.sql.Date;

public class Detail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail.detailId
     *
     * @mbg.generated
     */
    private Integer detailid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail.courseId
     *
     * @mbg.generated
     */
    private Integer courseid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail.relationshipId
     *
     * @mbg.generated
     */
    private Integer relationshipid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail.stuSta
     *
     * @mbg.generated
     */
    private String stusta;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail.course_date
     *
     * @mbg.generated
     */
    private Date courseDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail.extend1
     *
     * @mbg.generated
     */
    private String extend1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail.extend2
     *
     * @mbg.generated
     */
    private String extend2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail.detailId
     *
     * @return the value of detail.detailId
     *
     * @mbg.generated
     */
    public Integer getDetailid() {
        return detailid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail.detailId
     *
     * @param detailid the value for detail.detailId
     *
     * @mbg.generated
     */
    public void setDetailid(Integer detailid) {
        this.detailid = detailid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail.courseId
     *
     * @return the value of detail.courseId
     *
     * @mbg.generated
     */
    public Integer getCourseid() {
        return courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail.courseId
     *
     * @param courseid the value for detail.courseId
     *
     * @mbg.generated
     */
    public void setCourseid(Integer courseid) {
        this.courseid = courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail.relationshipId
     *
     * @return the value of detail.relationshipId
     *
     * @mbg.generated
     */
    public Integer getRelationshipid() {
        return relationshipid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail.relationshipId
     *
     * @param relationshipid the value for detail.relationshipId
     *
     * @mbg.generated
     */
    public void setRelationshipid(Integer relationshipid) {
        this.relationshipid = relationshipid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail.stuSta
     *
     * @return the value of detail.stuSta
     *
     * @mbg.generated
     */
    public String getStusta() {
        return stusta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail.stuSta
     *
     * @param stusta the value for detail.stuSta
     *
     * @mbg.generated
     */
    public void setStusta(String stusta) {
        this.stusta = stusta == null ? null : stusta.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail.course_date
     *
     * @return the value of detail.course_date
     *
     * @mbg.generated
     */
    public Date getCourseDate() {
        return courseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail.course_date
     *
     * @param courseDate the value for detail.course_date
     *
     * @mbg.generated
     */
    public void setCourseDate(Date courseDate) {
        this.courseDate = courseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail.extend1
     *
     * @return the value of detail.extend1
     *
     * @mbg.generated
     */
    public String getExtend1() {
        return extend1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail.extend1
     *
     * @param extend1 the value for detail.extend1
     *
     * @mbg.generated
     */
    public void setExtend1(String extend1) {
        this.extend1 = extend1 == null ? null : extend1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail.extend2
     *
     * @return the value of detail.extend2
     *
     * @mbg.generated
     */
    public String getExtend2() {
        return extend2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail.extend2
     *
     * @param extend2 the value for detail.extend2
     *
     * @mbg.generated
     */
    public void setExtend2(String extend2) {
        this.extend2 = extend2 == null ? null : extend2.trim();
    }
}