package com.singulee.carschool.pojo;

public class Driver {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.driverId
     *
     * @mbg.generated
     */
    private Integer driverid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.driverDescription
     *
     * @mbg.generated
     */
    private String driverdescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.extend1
     *
     * @mbg.generated
     */
    private String extend1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.driverId
     *
     * @return the value of driver.driverId
     *
     * @mbg.generated
     */
    public Integer getDriverid() {
        return driverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.driverId
     *
     * @param driverid the value for driver.driverId
     *
     * @mbg.generated
     */
    public void setDriverid(Integer driverid) {
        this.driverid = driverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.driverDescription
     *
     * @return the value of driver.driverDescription
     *
     * @mbg.generated
     */
    public String getDriverdescription() {
        return driverdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.driverDescription
     *
     * @param driverdescription the value for driver.driverDescription
     *
     * @mbg.generated
     */
    public void setDriverdescription(String driverdescription) {
        this.driverdescription = driverdescription == null ? null : driverdescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.extend1
     *
     * @return the value of driver.extend1
     *
     * @mbg.generated
     */
    public String getExtend1() {
        return extend1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.extend1
     *
     * @param extend1 the value for driver.extend1
     *
     * @mbg.generated
     */
    public void setExtend1(String extend1) {
        this.extend1 = extend1 == null ? null : extend1.trim();
    }
}