package com.singulee.carschool.pojo;

import java.util.Date;

public class Message {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.messageId
     *
     * @mbg.generated
     */
    private Integer messageid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.sendId
     *
     * @mbg.generated
     */
    private Integer sendid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.receiveId
     *
     * @mbg.generated
     */
    private Integer receiveid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.message
     *
     * @mbg.generated
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.sendDate
     *
     * @mbg.generated
     */
    private Date senddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.messageSta
     *
     * @mbg.generated
     */
    private Integer messagesta;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.messageId
     *
     * @return the value of message.messageId
     *
     * @mbg.generated
     */
    public Integer getMessageid() {
        return messageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.messageId
     *
     * @param messageid the value for message.messageId
     *
     * @mbg.generated
     */
    public void setMessageid(Integer messageid) {
        this.messageid = messageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.sendId
     *
     * @return the value of message.sendId
     *
     * @mbg.generated
     */
    public Integer getSendid() {
        return sendid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.sendId
     *
     * @param sendid the value for message.sendId
     *
     * @mbg.generated
     */
    public void setSendid(Integer sendid) {
        this.sendid = sendid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.receiveId
     *
     * @return the value of message.receiveId
     *
     * @mbg.generated
     */
    public Integer getReceiveid() {
        return receiveid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.receiveId
     *
     * @param receiveid the value for message.receiveId
     *
     * @mbg.generated
     */
    public void setReceiveid(Integer receiveid) {
        this.receiveid = receiveid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.message
     *
     * @return the value of message.message
     *
     * @mbg.generated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.message
     *
     * @param message the value for message.message
     *
     * @mbg.generated
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.sendDate
     *
     * @return the value of message.sendDate
     *
     * @mbg.generated
     */
    public Date getSenddate() {
        return senddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.sendDate
     *
     * @param senddate the value for message.sendDate
     *
     * @mbg.generated
     */
    public void setSenddate(Date senddate) {
        this.senddate = senddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.messageSta
     *
     * @return the value of message.messageSta
     *
     * @mbg.generated
     */
    public Integer getMessagesta() {
        return messagesta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.messageSta
     *
     * @param messagesta the value for message.messageSta
     *
     * @mbg.generated
     */
    public void setMessagesta(Integer messagesta) {
        this.messagesta = messagesta;
    }
}