package com.singulee.carschool.pojo;

import java.sql.Timestamp;
import java.util.Date;

public class Orders {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ordId
     *
     * @mbg.generated
     */
    private Integer ordid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.detailId
     *
     * @mbg.generated
     */
    private Integer detailid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.stuId
     *
     * @mbg.generated
     */
    private Integer stuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.logDate
     *
     * @mbg.generated
     */
    private Date logdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.states
     *
     * @mbg.generated
     */
    private Integer states;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.grade
     *
     * @mbg.generated
     */
    private Integer grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.log
     *
     * @mbg.generated
     */
    private String log;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.extend1
     *
     * @mbg.generated
     */
    private Timestamp extend1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ordId
     *
     * @return the value of orders.ordId
     *
     * @mbg.generated
     */
    public Integer getOrdid() {
        return ordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ordId
     *
     * @param ordid the value for orders.ordId
     *
     * @mbg.generated
     */
    public void setOrdid(Integer ordid) {
        this.ordid = ordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.detailId
     *
     * @return the value of orders.detailId
     *
     * @mbg.generated
     */
    public Integer getDetailid() {
        return detailid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.detailId
     *
     * @param detailid the value for orders.detailId
     *
     * @mbg.generated
     */
    public void setDetailid(Integer detailid) {
        this.detailid = detailid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.stuId
     *
     * @return the value of orders.stuId
     *
     * @mbg.generated
     */
    public Integer getStuid() {
        return stuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.stuId
     *
     * @param stuid the value for orders.stuId
     *
     * @mbg.generated
     */
    public void setStuid(Integer stuid) {
        this.stuid = stuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.logDate
     *
     * @return the value of orders.logDate
     *
     * @mbg.generated
     */
    public Date getLogdate() {
        return logdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.logDate
     *
     * @param logdate the value for orders.logDate
     *
     * @mbg.generated
     */
    public void setLogdate(Date logdate) {
        this.logdate = logdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.states
     *
     * @return the value of orders.states
     *
     * @mbg.generated
     */
    public Integer getStates() {
        return states;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.states
     *
     * @param states the value for orders.states
     *
     * @mbg.generated
     */
    public void setStates(Integer states) {
        this.states = states;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.grade
     *
     * @return the value of orders.grade
     *
     * @mbg.generated
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.grade
     *
     * @param grade the value for orders.grade
     *
     * @mbg.generated
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.log
     *
     * @return the value of orders.log
     *
     * @mbg.generated
     */
    public String getLog() {
        return log;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.log
     *
     * @param log the value for orders.log
     *
     * @mbg.generated
     */
    public void setLog(String log) {
        this.log = log == null ? null : log.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.extend1
     *
     * @return the value of orders.extend1
     *
     * @mbg.generated
     */
    public Timestamp getExtend1() {
        return extend1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.extend1
     *
     * @param extend1 the value for orders.extend1
     *
     * @mbg.generated
     */
    public void setExtend1(Timestamp extend1) {
        this.extend1 = extend1 ;
    }
}