package com.singulee.carschool.pojo;

import java.sql.Timestamp;

public class Relationship {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relationship.relationshipId
     *
     * @mbg.generated
     */
    private Integer relationshipid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relationship.teacherId
     *
     * @mbg.generated
     */
    private Integer teacherid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relationship.cartId
     *
     * @mbg.generated
     */
    private Integer cartid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relationship.startTime
     *
     * @mbg.generated
     */
    private Timestamp starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relationship.endTime
     *
     * @mbg.generated
     */
    private Timestamp endtime;

    private Cart cart;

    private Teacher teacher;

    public Cart getCart() {
        return cart;
    }

    public void setCart(Cart cart) {
        this.cart = cart;
    }

    public Teacher getTeacher() {
        return teacher;
    }

    public void setTeacher(Teacher teacher) {
        this.teacher = teacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relationship.relationshipId
     *
     * @return the value of relationship.relationshipId
     * @mbg.generated
     */
    public Integer getRelationshipid() {
        return relationshipid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relationship.relationshipId
     *
     * @param relationshipid the value for relationship.relationshipId
     * @mbg.generated
     */
    public void setRelationshipid(Integer relationshipid) {
        this.relationshipid = relationshipid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relationship.teacherId
     *
     * @return the value of relationship.teacherId
     * @mbg.generated
     */
    public Integer getTeacherid() {
        return teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relationship.teacherId
     *
     * @param teacherid the value for relationship.teacherId
     * @mbg.generated
     */
    public void setTeacherid(Integer teacherid) {
        this.teacherid = teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relationship.cartId
     *
     * @return the value of relationship.cartId
     * @mbg.generated
     */
    public Integer getCartid() {
        return cartid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relationship.cartId
     *
     * @param cartid the value for relationship.cartId
     * @mbg.generated
     */
    public void setCartid(Integer cartid) {
        this.cartid = cartid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relationship.startTime
     *
     * @return the value of relationship.startTime
     * @mbg.generated
     */
    public Timestamp getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relationship.startTime
     *
     * @param starttime the value for relationship.startTime
     * @mbg.generated
     */
    public void setStarttime(Timestamp starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relationship.endTime
     *
     * @return the value of relationship.endTime
     * @mbg.generated
     */
    public Timestamp getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relationship.endTime
     *
     * @param endtime the value for relationship.endTime
     * @mbg.generated
     */
    public void setEndtime(Timestamp endtime) {
        this.endtime = endtime;
    }
}